
const mongoose = require('mongoose');

const glossarySchema = new mongoose.Schema({
    novelId: { type: mongoose.Schema.Types.ObjectId, ref: 'Novel', required: true, index: true },
    term: { type: String, required: true }, // المصطلح الأصلي (إنجليزي)
    translation: { type: String, required: true }, // الترجمة المعتمدة
    autoGenerated: { type: Boolean, default: false } // هل تم استخراجه بواسطة الذكاء الاصطناعي؟
}, { timestamps: true });

// منع تكرار المصطلح لنفس الرواية
glossarySchema.index({ novelId: 1, term: 1 }, { unique: true });

const Glossary = mongoose.model('Glossary', glossarySchema);
module.exports = Glossary;
