const mongoose = require('mongoose');

const glossarySchema = new mongoose.Schema({
    novelId: { type: mongoose.Schema.Types.ObjectId, ref: 'Novel', required: true, index: true },
    term: { type: String, required: true }, // المصطلح الأصلي (إنجليزي)
    translation: { type: String, required: true }, // الترجمة المعتمدة
    autoGenerated: { type: Boolean, default: false } // هل تم استخراجه بواسطة الذكاء الاصطناعي؟
}, { 
    timestamps: true,
    autoIndex: true // يضمن بناء الفهارس المعرفة هنا
});

// منع تكرار نفس المصطلح داخل الرواية الواحدة
// مسموح بمصطلحات مختلفة لنفس الرواية، ومسموح بنفس المصطلح لروايات مختلفة
glossarySchema.index({ novelId: 1, term: 1 }, { unique: true, background: true });

const Glossary = mongoose.model('Glossary', glossarySchema);
module.exports = Glossary;
